### ISSUE TITLE
the icon doesn't appear

### ISSUE THREAD

**Issue by wf11** [turnermm/Updatable-Snippets-for-Dokuwiki#10]
hi
i installed the plugin, created a page called "snippets" with a list and there is no button appearing. cache cleared by touching conf/local.php.

what can I do?

**Comment by turnermm** [comment]
Hard to know. Try to delete the browser cache and reinstall the plugin.

**Comment by wf11** [comment]
I tryd this... No chance to get it running... So sad...

**Comment by turnermm** [comment]
What desktop do you use and which browser  (and have you tried another browser)?  What OS does your Dokuwiki run on and which version of DW are you using?

**Comment by turnermm** [comment]
A javascript issue has been fixed in the snippets plugin,  This may fix your problem.
