### ISSUE TITLE
Conflicts with tagfilter plugin

### ISSUE THREAD

**Issue by jscheiber** [turnermm/Updatable-Snippets-for-Dokuwiki#12]
With the "tagfilter" plugin installed, the "snippet" window looses its icons and functionality. 
DW Release: Hrun

**Comment by turnermm** [comment]
Check for javascript errors using firebug or the chrome browser. See where the problem originates.

**Comment by turnermm** [comment]
A javascript issue in the snippets plugin has been fixed.  This may fix your problem.
