### ISSUE TITLE
Popup compatibility with Bootstrap3 template

### ISSUE THREAD

**Issue by MarcosMenegazzo** [turnermm/Updatable-Snippets-for-Dokuwiki#18]
After changing my dokuwiki template to [Bootstrap 3](https://www.dokuwiki.org/template:bootstrap3), i noticed that the select Snippet dialog box is appearing with no styles at all. My question: is this something to fix in the Boostrap3 template or in the snippets plugin?

**Comment by turnermm** [comment]
I suspect the problem is with the Bootstrap template.  I just had a chance to test on two templates other than the dokwiki template.  Both worked.  One is my own, simple_sidebar, which is based on the old default template, and then on the arctic template, which is popular.   You could try moving the snippets css from the plugin/snippets directory to conf/userstyle.css. 
See: 
https://www.dokuwiki.org/config?s[]=userstyle.css#configuration_files
https://www.dokuwiki.org/config?s[]=userstyle.css#configuration_files

**Comment by MarcosMenegazzo** [comment]
Thanks for the suggestion. That solves half of the problem, because the page preview is also no styled with bootstrap 3 theme. Maybe i need to verify how dokuwiki include the current css's and replicate the instructions in snippets plugin, what do you think? Is it possible?

**Comment by turnermm** [comment]
I have no experience with Bootstrap 3, but I just downloaded it and tested the preview.  If by 'preview' you mean Dokuwiki's preview in the editor, then I had no trouble.  The preview worked for me. Is it possible that there is a conflict with one of your plugins?  If so, disable all your plugins (including the userstyle.css) to see which, if any, plugin is causing the problem.  Then re-enable them one at a time.

**Comment by MarcosMenegazzo** [comment]
@turnermm  checking #6 i found:

> This turned out to be fixable from within the snippets plugin itself and that has been done.

Is this fixed at master?

**Comment by turnermm** [comment]
That seems to have been fixed, yes.  There was a null pointer error which showed up in some cases, which was there from before I adopted the plugin.  If you are familiar with the chrome or firefox javascript debuggers, you could check if there is an error showing up.  But, as I said above, I did download and install the Bootstrap template and had no problems with snippets.

**Comment by lukaspour** [comment]
@MarcosMenegazzo were you able to solve this problem? I am having the same issue. thank you very much for your suggestion

**Comment by MarcosMenegazzo** [comment]
@lukaspour sorry, other priorities arrived. With Detritus, the default theme, and not using the folded plugin will make it work. So here, for now, i only reverted to default theme and disabled the folded plugin.

I've planned to prototype a vagrant box and install a fresh new stable dokuwiki, the bootstrap 3 theme (Giuseppe Di Terlizzi version), the snippets plugin, and see if the problem persists, but I currently have no time for this. 

Have you tried something similar?

**Comment by turnermm** [comment]
@MarcosMenegazzo As I said earlier, I've tested snippets w. Bootstrap and had no problems, and while not at my office right now, I'm pretty sure it was with detritus.

**Comment by drilus** [comment]
I believe I have an issue with bootstrap3 as well.

Here is what the popup window looks like:
<img width="912" alt="screen shot 2017-02-20 at 4 15 16 pm" src="https://cloud.githubusercontent.com/assets/1356350/23142038/e0fb111e-f787-11e6-8297-a6f33c580834.png">

Here is a screenshot of my console log:
![screen shot 2017-02-20 at 4 10 58 pm](https://cloud.githubusercontent.com/assets/1356350/23141947/47bf8228-f787-11e6-83e9-3f53c9667d9b.png)

I'm using the following plugin for bootstrap3: https://www.dokuwiki.org/template:bootstrap3

**Comment by turnermm** [comment]
I don't see anything here which applies to snippets:  `dw_mode` is from bootstrap3.  To see more easily what is going on, turn off javascript and css compression.  Then you should be able to see where in the code the errors are, using the debugger.

**Comment by turnermm** [comment]
When you have a javascript error such as this, it can have a cascading effect,  affecting other javascript, which is why it shows up in the broken snippets panel.  But the error is not coming from snippets.

**Comment by drilus** [comment]
Turns out there were some modules missing from the Boostrap3 template. I guess this could be due to a corrupted install / update.

Thanks @turnermm
