### ISSUE TITLE
Error on anonymous function (helper.php:148)

### ISSUE THREAD

**Issue by MichaelGr** [turnermm/Updatable-Snippets-for-Dokuwiki#2]
Parse error: syntax error, unexpected T_FUNCTION in /home/artatom_ru/data/www/wiki.artatom.ru/lib/plugins/snippets/helper.php on line 148

My wiki hosted on web server with php 5.2.17 that has not closures.
I have repaired it now, but maybe someone else will face the same problem in future.

**Comment by turnermm** [comment]
I am a slight step ahead of the system requirements, but with the next version of dokuwiki there are plans to require php 5.3, which implements the new `preg_replace_callback` syntax.  I'm glad you could fix it.  But it's rarely an issue.  I've been using it in ckgedit for at least a year, and that has a good size user base, and I've only had a few people needing assistance.  So there I've made available pre-5.3 versions of the file where it is a problem.

**Comment by farmascript** [comment]
The same problem here. What can i change in de sourcecode in helper.php to fix the problem?
Thnx.

**Comment by turnermm** [comment]
I will get back to you with a fix

**Comment by turnermm** [comment]
Use this branch:
 https://github.com/turnermm/Updatable-Snippets-for-Dokuwiki/archive/pre_53.zip

**Comment by farmascript** [comment]
Thanks!
