### ISSUE TITLE
Popup compatibility with folded plugin

### ISSUE THREAD

**Issue by moz0817** [turnermm/Updatable-Snippets-for-Dokuwiki#21]
I noticed a similar behavior (issue #18: no 
styles with bootstrap3 template) when I used the plugin together with folded plugin. 
I've tested this in different environments and at last within a fresh new installation: Template **dokuwiki**, only with this two plugins.
**Folded not active**:
![snippet ok](https://cloud.githubusercontent.com/assets/2591552/15395327/8a283ca2-1dd7-11e6-836a-935678faef4b.png)

**Folded active**:
![snippet fail](https://cloud.githubusercontent.com/assets/2591552/15395334/8d68fd3e-1dd7-11e6-8736-11124925c9db.png)

The same question:  Is this an issue for your plugin or the folded one?

**Comment by turnermm** [comment]
See: https://github.com/turnermm/Updatable-Snippets-for-Dokuwiki/issues/6

There seem to be various incompatibilities with the folded plugin.  I can only give you the same answers which I gave to the other users who posted about folded.

**Comment by moz0817** [comment]
Thanks and sorry. I did'nt read this issue.
