### ISSUE TITLE
„No button“-Issue

### ISSUE THREAD

**Issue by punk-t** [turnermm/Updatable-Snippets-for-Dokuwiki#25]
I had the same issue as mentioned in #10, and couldn't resolve it using the hints given there. After lots of trying, cache deleting and silent crying I did a clean vanilla install of dokuwiki with just the elementary plugins.

I installed your Snippets plugin but the „insert Templates“-button didn't want to show up. Finally I gave the Snippets Original plugin a try and installed [as described here](https://www.dokuwiki.org/plugin:snippets:original). This brought up the button. After patching the original plugin with yours using the normal extension manager doesn't have any further effect to the button, it stays in the editors toolbar now.

Maybe you want to give those a hint who have the same problem.

**Comment by turnermm** [comment]
Did you follow this instruction:

> IMPORTANT: You have to invalidate/delete the cache before the new button appears in the toolbar. 

If so, I suspect that is what helped.

**Comment by linhua55** [comment]
I also can't see the button. I delete the cache in Chrome(and also use Chrome Incognito Mode(Ctrl+Shift+N)), and dokuwiki(https://www.dokuwiki.org/caching)
I use this docker.
https://hub.docker.com/r/linhua/docker-dokuwiki/

**Comment by turnermm** [comment]
I'm not familiar with your docker setup, nor with the effects of Chrome's incognito mode.

**Comment by linhua55** [comment]
Thanks. I add the snippets_page(snippets), and add a unordered list, just like https://www.dokuwiki.org/plugin:snippets#usage .  and also delete the cache. Finally, it works well. The button comes out.

**Comment by turnermm** [comment]
I am pleased that it is working.  So l will close this issue.
