### ISSUE TITLE
Not compatible with Frusterick Manners (?)

### ISSUE THREAD

**Issue by SonoDavid** [turnermm/Updatable-Snippets-for-Dokuwiki#29]
When I add a new snippet to the current snippets page, it doesn't get added to the Snippets (Template manager) screen that opens when I click the templates button in the edit bar.

This happened since the update to Frusterick Manners, so I think (hope) it has something to do with the version of dokuwiki I'm using. Also on dokuwiki snippets page, snippets plugin page doesn't seem compatible with the new dokuwiki version (still has question mark next to the compatibility), so maybe I'm not alone.

**Comment by turnermm** [comment]
![snippets_list](https://cloud.githubusercontent.com/assets/176447/25042518/44f7668e-20de-11e7-9887-d0cd74bc2bfa.png)
If this menu is what you mean, then all I can suggest is that you clear out your browser cache and possibly the dokuwiki cache.  The list of templates is simply a dokuwiki page.  See what happens by the way if you use a different browser.

There is no conflict with F-M, as far as I can tell.

**Comment by SonoDavid** [comment]
Thanks! It seems like I just used the wrong settings in the Configuration Screen. It referred to the page 'snippets' while the correct link was 'snippets:start'.
I was also confused because the 'snippets' page didn't show up in the dokuwiki sitemap.
