### ISSUE TITLE
snippets pop-up window is empty

### ISSUE THREAD

**Issue by RalphGL** [turnermm/Updatable-Snippets-for-Dokuwiki#42]
After installing the plugin and clicking the new button there opens a new window - but it is empty. This behavior occurs in both firefox and chrome (Windows 8.1).

**Comment by turnermm** [comment]
Make sure that you have followed the instructions carefully that you will find on the plugin page:  https://www.dokuwiki.org/plugin:snippets#usage

Otherwise, I can't help, since a quick test shows that the plugin is working as described.
