### ISSUE TITLE
there is no insert button in pop-up window

### ISSUE THREAD

**Issue by qw918** [turnermm/Updatable-Snippets-for-Dokuwiki#43]
in pop-up window,when i click the left link ,the page replaced the  top window, so i can't insert the snippet into the editing window at the current cursor location.

**Comment by turnermm** [comment]
Truthfully, I don't understand this.  What left link,what page?  Do you get a pop-up which looks like the pop-up illustrated on the plugin page at dokuwi.org?  Have you read the documentation? What browser are you using? what OS does this happen on? Etc. Have you checked the browser tools for javascript errors?

**Comment by qw918** [comment]
> 
first open the pop-up windown:
![asdsd_20220113132146](https://user-images.githubusercontent.com/6084946/149270575-1eed466f-766b-4a60-bab0-5e6b6f3aea8f.png)
after click the link in the left list...
![asdasd_20220113132048](https://user-images.githubusercontent.com/6084946/149270669-0801c4f7-3496-4489-8c6c-9231d60fd6b7.png)

**Comment by turnermm** [comment]
These pictures don't help much.   Is the first image, an image of your snippets index? Well, if so, it isn't showing the list of snippets. And what does the second image represent--is it one of your pages?   And what did you click on to get to it?

 Have you created a page with an unordered list of pages that link to your snippets?  Because your image doesn't show the list.  And have you properly identified this page in the configuration settings?

**Comment by fougeresagglo** [comment]
Hello,
I have the same problem. When I click on the toolbar button, a new window opens with the list of snippets but no icon to insert the snippet in the current page (image 1).  When I click on one of the snippets in the list I get image 2.
My "snippets" page is made like this:
```
  * [[snippet_1|]]
  * [[snippet_2|General Instructions]]
  * [[snippet_3|Valid Users]]
```

**Comment by turnermm** [comment]
I can't check this out because all I'll have access to for the next two or three weeks is my phone. I'll see what I can find out when I can get back to my laptop.

**Comment by fougeresagglo** [comment]
Hello, if necessary, I can do some tests or provide you with more information.

**Comment by turnermm** [comment]
See what you can come up with. Thnx

**Comment by fougeresagglo** [comment]
The problem is I don't know where to start... an idea of the tests to be carried out that might give you relevant information?

**Comment by turnermm** [comment]
You could check your php/system error Log for php errors and if you know how check your browser console log for any JavaScript errors

**Comment by fougeresagglo** [comment]
Looking at the javascript errors in the console, I discovered that there was an error on another plugin that was not functional. I just turned off the plugin and now it works. I believe that qw918 has the same problem and that the demand can be closed.

**Comment by turnermm** [comment]
Thank you
