### ISSUE TITLE
replacement strings not working in snippets

### ISSUE THREAD

**Issue by simon-r-white** [turnermm/Updatable-Snippets-for-Dokuwiki#8]
I've installed the snippets plugin, but can't seem to get the replacement strings working.

I've testing using templates, and @NS@ works fine... I know inside a snippet it needs to be #NS#.

However, the replacement doesn't occur.

I'm not really sure how to go about finding the problem.

**Comment by turnermm** [comment]
```
file: #!FILE#
USER: @USER@
mail: @MAIL@
date: @DATE@
Namespace:  #NS#

```

Create a snippet using the above code.  Do you get a result?  If not, have you followed the instructions for creating namespace snippets?  
https://www.dokuwiki.org/doku.php?id=plugin:snippets#creating_links_to_namespace_templates

**Comment by simon-r-white** [comment]
Oh... possible confusion. Does that mean the replacement only occurs for namespace snippets?

I was hoping it would work for all snippets (even non-template ones).

Also, I use the TemplatePageName Plugin for templates, so I wasn't quite sure how to combine the snippets-plugin with that.

**Comment by turnermm** [comment]
Yes. only for Namespace templates.  

Have you tried it with TemplatePageName?  Snippets should work with the c_ type templates.
